# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewYorkTimesApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewYorkTimesApp
  pod 'Shimmer'
  pod 'DZNEmptyDataSet'
  pod 'ReachabilitySwift'
  pod "BPStatusBarAlert"

  target 'NewYorkTimesAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
